import { useContext } from 'react'

import Head from 'next/head'

import styled from '@emotion/styled'

import {
  Content,
  ModalPlayers,
  Nav,
} from '../components'
import { AppContext } from './_app'

const Main = styled.main`
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
`

const Home = () => {
  const { modal } = useContext(AppContext)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {modal && <ModalPlayers />}
      <Nav />
      <Content />

    </div>
  )
}
export default Home